### ISSUE TITLE
Hyperlinks turn into "clickable/selectable" text.

### ISSUE THREAD

**Issue by 54m4d** [ChristopherBull/Clear-Links#15]
I encountered a minor issue where hyperlinks transform into "clickable/selectable" text. This anomaly occurs primarily during the initial hover, but it can also occur after multiple back-and-forth hovers, indicating a somewhat inconsistent behavior.

I was able to reproduce the issue on https://github.com/issues

As you can see below, the cursor turned from a hand to a text-select cursor. This should normally be a clickable link.

![Capture 04_01_2024 16_39_30](https://github.com/ChristopherBull/Clear-Links/assets/52612348/497ed6b1-33ed-4fc5-bbe2-edd0cb9885ab)

**Comment by ChristopherBull** [comment]
Hi. Thank you for reporting this issue. I too had seen this on occasion, so it is good to have confirmation. This was occurring during the transition to v3. I have not been able to replicate this in recent versions of Chrome and with the latest version of the extension.

I'll leave this Issue open for now as I would like to get confirmation from you whether you are still experiencing it. Otherwise, I'll close it in the near future and presume it was fixed along with updates and fixes in recent versions.

**Comment by 54m4d** [comment]
I've just attempted to replicate the issue, and unfortunately, it persists. Pay close attention to how it turns from **link selection** to **text selection** when hovering over the "Preview" above the GitHub comment box.

Disabling the extension does not lead to any such behavior, so it's obviously the culprit, unfortunately.

<details>
<summary>Screenshot</summary>
<img src=https://github.com/ChristopherBull/Clear-Links/assets/52612348/1236fbd8-c712-48eb-b202-de3c4c1d50d0)>
</details>

**Comment by 54m4d** [comment]
Hi, the issue persists in version 3.5.0 and has worsened. It now also causes the cursor to glitch in text boxes like this one. I had to disable it to make sure I can use this section.

**Comment by ChristopherBull** [comment]
I have tried to replicate it again, but no luck.

For reference:
Chrome version: 127.0.6533.120
OS: MacOS 14.6.1

Could you provide your Chrome and OS versions, please?

**Comment by 54m4d** [comment]
Hi, the issue might be due to a conflict with another extension. I'll see if I can isolate the problem.
